const assert = require("node:assert/strict");
const Database = require("better-sqlite3");
const { randomUUID } = require("node:crypto");
const { spawnSync } = require("node:child_process");
const path = require("node:path");

module.exports = async function ({ request, session, database, account, restart, root, directory, env }) {
  const db = new Database(database);
  try {
    const owner = db.prepare("SELECT id FROM users WHERE email=?").get(account.email).id;
    const other = db.prepare("SELECT id FROM users WHERE email='other@example.com'").get().id;
    const call = (method, suffix, body, headers) => request(method, "/api/v2/library" + suffix, body, session, headers);
    const checked = async (promise, expected = 200) => {
      const response = await promise;
      assert.equal(response.status, expected, await response.clone().text());
      return response.status === 204 ? null : response.json();
    };
    assert.equal((await request("GET", "/api/library")).status, 401);
    const tag = await checked(call("POST", "/labels", { kind: "tag", name: "Research" }), 201);
    const collection = await checked(call("POST", "/labels", { kind: "collection", name: "Reading" }), 201);
    assert.deepEqual(Object.keys(tag).sort(), ["id", "kind", "name"]);
    await checked(call("POST", "/labels", { kind: "tag", name: " research " }), 409);
    await checked(call("POST", "/labels", { kind: "tag", name: "Ｒｅｓｅａｒｃｈ" }), 409);
    for (const name of [null, [], {}, "", "a".repeat(81), "hello\nworld"]) await checked(call("POST", "/labels", { kind: "tag", name }), 400);
    await checked(call("POST", "/labels", { kind: "admin", name: "No" }), 400);
    const foreignLabel = randomUUID();
    db.prepare("INSERT INTO library_labels(id,user_id,kind,name,name_key) VALUES(?,?,'tag','Private','private')").run(foreignLabel, other);
    await checked(call("PATCH", "/labels/" + foreignLabel, { kind: "tag", name: "Takeover" }), 404);
    await checked(call("DELETE", "/labels/" + foreignLabel), 404);
    await checked(call("POST", "/labels", { kind: "tag", name: "CSRF" }, { Origin: "https://evil.example" }), 403);
    await checked(call("POST", "/labels", { kind: "tag", name: "Opaque" }, { Origin: "null" }), 403);
    assert.equal((await request("POST", "/settings/library", { operation: "save_label", kind: "tag", name: "CSRF" }, session,
      { Origin: "https://evil.example", Accept: "text/html" })).status, 403);
    const ids = [];
    for (let n = 0; n < 3; n++) {
      const row = await checked(request("POST", "/api/links", { target: `https://192.0.2.1/library_${n}`, customurl: "lib-" + randomUUID() }, session), 201);
      ids.push(row.id);
    }
    const bulk = (action, selected = ids.slice(0, 2), label_id, headers) => call("POST", "/bulk", { action, ids: selected, label_id }, headers);
    const before = db.prepare("SELECT * FROM links WHERE uuid=?").get(ids[0]);
    await checked(bulk("add_label", undefined, tag.id));
    await checked(bulk("add_label", [ids[0]], collection.id));
    await checked(bulk("add_label", undefined, tag.id));
    assert.equal(db.prepare("SELECT count(*) n FROM library_link_labels WHERE label_id=?").get(tag.id).n, 2);
    let result = await checked(call("GET", "?tag=" + tag.id + "&collection=" + collection.id));
    assert.deepEqual(result.data.map(row => row.id), [ids[0]]);
    assert.equal(result.total, 1);
    assert(!JSON.stringify(result).includes("Private"));
    assert.equal(result.data[0].password, false);
    assert(!("user_id" in result.data[0]));
    assert.equal((await checked(call("GET", "?q=library_0"))).total, 1);
    assert.equal((await checked(call("GET", "?q=%25"))).total, 0, "Search wildcards are literal");
    for (const query of ["?q[x]=x", "?tag[x]=x", "?state=invalid", "?page=-1", "?page=1.5", "?saved[x]=x"]) await checked(call("GET", query), 400);
    await checked(call("GET", "?tag=" + foreignLabel), 404);
    const saved = await checked(call("POST", "/filters", { name: "Reading queue", filters: { tag: tag.id, collection: collection.id, state: "active" } }), 201);
    const foreignFilter = randomUUID();
    db.prepare("INSERT INTO library_filters(id,user_id,name,name_key,filters) VALUES(?,?,'Private filter','private filter','{}')").run(foreignFilter, other);
    await checked(call("GET", "?saved=" + foreignFilter), 404);
    await checked(call("PATCH", "/filters/" + foreignFilter, { name: "Stolen", filters: {} }), 404);
    await checked(call("DELETE", "/filters/" + foreignFilter), 404);
    await checked(call("POST", "/filters", { name: " reading queue ", filters: {} }), 409);
    await checked(call("POST", "/filters", { name: "Private", filters: { tag: foreignLabel } }), 404);
    await checked(call("DELETE", "/labels/" + collection.id), 409, "Saved filter must not widen silently");
    await checked(call("PATCH", "/labels/" + tag.id, { kind: "tag", name: "References" }));
    result = await checked(call("GET", "?saved=" + saved.id));
    assert.equal(result.total, 1);
    assert.equal(result.data[0].labels.find(label => label.id === tag.id).name, "References");
    await restart();
    assert.equal((await checked(call("GET", "?saved=" + saved.id))).total, 1);
    for (const selected of [[], [ids[0], ids[0]], [ids[0], randomUUID()], Array(101).fill(ids[0])]) {
      await checked(bulk("pause", selected), selected.length === 2 && selected[0] !== selected[1] ? 404 : 400);
      assert.equal(db.prepare("SELECT paused FROM links WHERE uuid=?").get(ids[0]).paused, 0);
    }
    db.prepare("UPDATE links SET user_id=? WHERE uuid=?").run(other, ids[1]);
    await checked(bulk("pause"), 404, "Admin must not cross ownership boundaries");
    db.prepare("UPDATE links SET user_id=? WHERE uuid=?").run(owner, ids[1]);
    db.prepare("UPDATE links SET banned=1 WHERE uuid=?").run(ids[1]);
    await checked(bulk("pause"), 409);
    db.prepare("UPDATE links SET banned=0 WHERE uuid=?").run(ids[1]);
    await checked(bulk("add_label", undefined, foreignLabel), 404);
    await checked(bulk("trash", undefined, undefined, { Origin: "https://evil.example" }), 403);
    const readToken = (await checked(request("POST", "/api/tokens", { name: "Library read", scopes: ["links:read"] }, session), 201)).token;
    const limitedToken = (await checked(request("POST", "/api/tokens", { name: "Library default", scopes: ["links:read", "links:update"], domain_scope: "default" }, session), 201)).token;
    const deleteToken = (await checked(request("POST", "/api/tokens", { name: "Library delete", scopes: ["links:delete"] }, session), 201)).token;
    await checked(bulk("pause", undefined, undefined, { "X-API-Key": readToken }), 403);
    assert.equal((await request("POST", "/settings/library", { operation: "bulk", action: "pause", ids }, session,
      { "X-API-Key": readToken, Accept: "text/html" })).status, 403);
    await checked(bulk("trash", undefined, undefined, { "X-API-Key": limitedToken }), 403);
    await checked(call("POST", "/labels", { kind: "tag", name: "Narrow" }, { "X-API-Key": limitedToken }), 403);
    await checked(call("GET", "?saved=" + saved.id, undefined, { "X-API-Key": limitedToken }), 403);
    const domainId = Number(db.prepare("INSERT INTO domains(uuid,address,user_id) VALUES(?,?,?)").run(randomUUID(), "library.example", owner).lastInsertRowid);
    db.prepare("UPDATE links SET domain_id=? WHERE uuid=?").run(domainId, ids[1]);
    await checked(bulk("pause", undefined, undefined, { "X-API-Key": limitedToken }), 404);
    result = await checked(call("GET", "?q=library_", undefined, { "X-API-Key": limitedToken }));
    assert(!result.data.some(row => row.id === ids[1]));
    assert.deepEqual(result.labels, []);
    assert.deepEqual(result.saved_filters, []);
    db.prepare("UPDATE links SET domain_id=NULL WHERE uuid=?").run(ids[1]);
    // Force a failure after the first row to prove database rollback, not precheck alone.
    const secondId = db.prepare("SELECT id FROM links WHERE uuid=?").get(ids[1]).id;
    db.exec(`CREATE TRIGGER library_fail BEFORE UPDATE OF paused ON links WHEN NEW.id=${secondId} BEGIN SELECT RAISE(ABORT, 'fixture'); END`);
    await checked(bulk("pause"), 500);
    assert.equal(db.prepare("SELECT paused FROM links WHERE uuid=?").get(ids[0]).paused, 0);
    db.exec("DROP TRIGGER library_fail");
    await checked(bulk("pause", undefined, undefined, { "X-API-Key": limitedToken }));
    assert.equal((await request("GET", "/" + before.address)).status, 410);
    assert.equal((await checked(call("GET", "?tag=" + tag.id + "&state=paused"))).total, 2);
    await checked(bulk("resume"));
    assert.equal((await request("GET", "/" + before.address)).status, 302);
    await checked(bulk("remove_label", [ids[0]], tag.id));
    assert.equal((await checked(call("GET", "?saved=" + saved.id))).total, 0);
    await checked(bulk("add_label", [ids[0]], tag.id));
    await checked(bulk("trash", undefined, undefined, { "X-API-Key": deleteToken }));
    assert.equal((await checked(call("GET", "?tag=" + tag.id + "&state=trash"))).total, 2);
    db.prepare("UPDATE links SET archived_domain='retired.library.example' WHERE uuid=?").run(ids[1]);
    const archived = (await checked(call("GET", "?state=trash"))).data.find(row => row.id === ids[1]);
    assert.equal(archived.domain, "retired.library.example");
    assert(archived.link.includes("retired.library.example/"), "Archived links retain their original host, never the default domain");
    assert.equal((await checked(call("GET", "?state=trash", undefined, { "X-API-Key": limitedToken }))).data.some(row => row.id === ids[1]), false);
    assert.equal((await request("GET", "/" + before.address)).status, 410);
    await checked(request("POST", "/api/links/" + ids[0] + "/restore", {}, session));
    assert.equal((await checked(call("GET", "?saved=" + saved.id))).total, 1, "Restore retains organization");
    const after = db.prepare("SELECT * FROM links WHERE uuid=?").get(ids[0]);
    for (const field of ["target", "uuid", "address", "password", "user_id", "max_visits", "starts_at", "ends_at"]) assert.equal(after[field], before[field], field);
    const history = await checked(request("GET", "/api/links/" + ids[0] + "/history", undefined, session));
    assert(history.data.some(row => row.action === "organized"));
    assert(!JSON.stringify(history).includes("References"), "History stores field names, not label values");
    await checked(call("PATCH", "/filters/" + saved.id, { name: "Updated", filters: { q: "library_2" } }));
    assert.equal((await checked(call("GET", "?saved=" + saved.id))).data[0].id, ids[2]);
    await checked(call("DELETE", "/labels/" + collection.id), 204);
    assert(db.prepare("SELECT id FROM links WHERE uuid=?").get(ids[0]));
    await checked(call("DELETE", "/filters/" + saved.id), 204);
    const down = spawnSync(process.execPath, [path.join(root, "node_modules/knex/bin/cli.js"), "--knexfile", path.join(root, "knexfile.js"), "migrate:down", "20260914003000_library.js"], { cwd: directory, env, timeout: 60000, encoding: "utf8" });
    assert.notEqual(down.status, 0, "Populated library downgrade must refuse data loss");
    assert.equal(db.pragma("quick_check", { simple: true }), "ok");
    assert.deepEqual(db.pragma("foreign_key_check"), []);
    console.log("PASS: library labels, collections, saved filters, exact search, atomic bulk rollback, CSRF/owner/domain/scope boundaries, persistence, history and guarded downgrade");
  } finally { db.close(); }
};
