const assert = require("node:assert/strict");
const { randomUUID } = require("node:crypto");
const { spawnSync } = require("node:child_process");
const path = require("node:path");
const Database = require("better-sqlite3");
module.exports = async ({ request, session, database, account, restart, root, directory, env }) => {
  const db = new Database(database), owner = db.prepare("SELECT id FROM users WHERE email=?").get(account.email).id;
  const check = async (response, expected = 200) => { response = await response; assert.equal(response.status, expected, await response.clone().text()); return expected === 204 ? null : response.json(); };
  const code = value => spawnSync(process.execPath, ["-e", `(async()=>{const assert=require('node:assert/strict');const h=require(${JSON.stringify(path.join(root, "server/link-health"))});const safe=require(${JSON.stringify(path.join(root, "server/safe-http"))});const db=require(${JSON.stringify(path.join(root, "server/knex"))});${value};await db.destroy()})().catch(e=>{console.error(e.stack);process.exit(1)})`], { cwd: directory, env, encoding: "utf8", timeout: 30000 });
  const runCode = value => { const result = code(value); assert.equal(result.status, 0, result.stderr); return result.stdout; };
  try {
    runCode(`for(const url of ['http://example.com/','https://localhost/','https://127.0.0.1/','https://[::1]/','https://u:p@example.com/','https://example.com:444/','https://example.com/?access_token=secret','https://example.com/?api_key=secret','https://example.com/\\\\x'])assert.throws(()=>h.probeURL(url));
      assert.equal(h.probeURL('https://example.com/path?q=ok#private'),'https://example.com/path?q=ok');
      let calls=[];safe.send=async(u,o)=>{calls.push([u,o]);return{status:302}};
      let r=await h.probe({name:'Default',target:'https://example.com/path#part'});assert.equal(r.code,'REDIRECT');assert.equal(calls.length,1);assert.equal(calls[0][1].method,'HEAD');assert.equal(calls[0][1].body,undefined);assert(!JSON.stringify(calls).includes('Cookie'));
      for(const [s,c] of [[204,'OK'],[401,'ACCESS_RESTRICTED'],[403,'ACCESS_RESTRICTED'],[429,'ACCESS_RESTRICTED'],[405,'HEAD_UNSUPPORTED'],[501,'HEAD_UNSUPPORTED'],[503,'HTTP_ERROR']])assert.equal(h.classification(s),c);
      for(const c of ['ADDRESS_DENIED','DNS_FAILED','TIMEOUT','CONNECTION_FAILED','UNEXPECTED']){safe.send=async()=>{throw Object.assign(new Error('secret destination body'),{code:c})};r=await h.probe({name:'Default',target:'https://example.com/'});assert.equal(r.code,c==='UNEXPECTED'?'CHECK_FAILED':c);assert(!JSON.stringify(r).includes('secret destination'));}`);
    // Create offline without DNS, then seed the public hostname exercised by probe stubs.
    const link = await check(request("POST", "/api/links", { customurl: "health-" + randomUUID(), target: "https://192.0.2.1/health#fragment" }, session), 201);
    const id = db.prepare("SELECT id FROM links WHERE uuid=?").get(link.id).id, endpoint = "/api/links/" + link.id + "/health";
    link.target = "https://example.com/health#fragment";
    db.prepare("UPDATE links SET target=? WHERE id=?").run(link.target, id);
    const config = { enabled: true, interval_hours: 24, revision: 0 };
    const initial = await check(request("GET", endpoint, undefined, session)); assert.equal(initial.enabled, false); assert.equal(initial.revision, 0);
    await check(request("GET", endpoint), 401); await check(request("GET", "/api/links/health"), 401);
    assert.equal((await request("GET", "/link/health/" + link.id, undefined, session, { Accept: "text/html" })).status, 200);
    for (const input of [{ ...config, enabled: "true" }, { ...config, interval_hours: 0 }, { ...config, interval_hours: 169 }, { ...config, revision: -1 }, { ...config, user_id: 1 }]) await check(request("PUT", endpoint, input, session), 400);
    await check(request("PUT", endpoint, config, session, { Origin: "https://evil.invalid" }), 403);
    const foreign = Number(db.prepare("INSERT INTO users(email,password,role,verified) SELECT ?,password,'ADMIN',1 FROM users WHERE id=?").run(randomUUID() + "@example.invalid", owner).lastInsertRowid);
    const foreignSession = require("jsonwebtoken").sign({ iss: "ApiAuth", sub: foreign }, env.JWT_SECRET, { expiresIn: 600 });
    await check(request("GET", endpoint, undefined, foreignSession), 404);
    await check(request("PUT", endpoint, config, foreignSession), 404);
    const token = (scopes, domain_scope = "all") => check(request("POST", "/api/tokens", { name: "Monitoring", scopes, domain_scope }, session), 201);
    const reader = await token(["links:read"], "default"), writer = await token(["links:update"], "default");
    const rh = { "X-API-Key": reader.token }, wh = { "X-API-Key": writer.token };
    await check(request("GET", endpoint, undefined, undefined, rh));
    await check(request("PUT", endpoint, config, session, rh), 403);
    await check(request("POST", endpoint + "/check", { revision: 0 }, session, rh), 403);
    await check(request("GET", "/link/health/" + link.id, undefined, session, rh), 403);
    await check(request("GET", endpoint, undefined, session, wh), 403);
    let current = await check(request("PUT", endpoint, config, undefined, wh)); assert.equal(current.revision, 1); assert.equal(current.state, "pending");
    assert.equal((await request("GET", endpoint, undefined, session)).headers.get("cache-control"), "private, no-store");
    assert.equal((await check(request("GET", "/api/links/health", undefined, foreignSession))).data.length, 0);
    assert((await check(request("GET", "/api/links/health", undefined, undefined, rh))).data.some(row => row.id === link.id));
    await check(request("GET", "/api/links/health?before=NaN", undefined, session), 400);
    await check(request("PUT", endpoint, config, undefined, wh), 409);
    await check(request("POST", endpoint + "/check", { revision: 1 }, undefined, wh), 202);
    await check(request("POST", endpoint + "/check", { revision: 1 }, undefined, wh), 429);
    const state = () => db.prepare("SELECT * FROM link_health WHERE link_id=?").get(id);
    const resetGate = () => db.prepare("UPDATE health_worker SET next_claim_at=0 WHERE id=1").run();
    const cycle = extra => runCode(`safe.send=async()=>({status:204});${extra || ""};const row=await h.claim();assert.equal(row.link_id,${id});await h.run(row)`);
    const counters = db.prepare("SELECT redirect_count,visit_count FROM links WHERE id=?").get(id);
    const domain = Number(db.prepare("INSERT INTO domains(uuid,address,user_id,banned) VALUES(?,?,?,0)").run(randomUUID(), "health.example.invalid", owner).lastInsertRowid);
    db.prepare("UPDATE links SET domain_id=? WHERE id=?").run(domain, id);
    await check(request("GET", endpoint, undefined, session, rh), 404);
    await check(request("PUT", endpoint, { ...config, revision: 1 }, session, wh), 404);
    assert(!(await check(request("GET", "/api/links/health", undefined, session, rh))).data.some(row => row.id === link.id));
    db.prepare("UPDATE domains SET user_id=? WHERE id=?").run(foreign, domain);
    resetGate(); cycle(); assert.equal(state().state, "authorization_required");
    await check(request("GET", endpoint, undefined, session), 410);
    db.prepare("UPDATE domains SET user_id=? WHERE id=?").run(owner, domain);
    db.prepare("UPDATE links SET domain_id=NULL WHERE id=?").run(id);
    assert.equal(state().enabled, 0);
    await check(request("PUT", endpoint, { ...config, revision: state().revision }, session));
    db.prepare("UPDATE link_health SET next_at=0 WHERE link_id=?").run(id);
    resetGate(); cycle(); assert.equal(state().state, "healthy"); assert(state().checked_at); assert.equal(JSON.parse(state().results)[0].code, "OK");
    assert.deepEqual(db.prepare("SELECT redirect_count,visit_count FROM links WHERE id=?").get(id), counters, "Probes do not count visits or consume quota");
    const events = db.prepare("SELECT type,payload FROM management_events WHERE user_id=?").all(owner).filter(row => JSON.parse(row.payload).data.link_id === link.id);
    assert(events.some(row => row.type === "link.health_configured")); assert(events.some(row => row.type === "link.health_changed"));
    runCode(`assert.equal(await h.claim(),null)`);
    db.prepare("UPDATE link_health SET next_at=0 WHERE link_id=?").run(id); resetGate();
    runCode(`const rows=await Promise.all([h.claim(),h.claim()]);assert.equal(rows.filter(Boolean).length,1)`);
    await restart(); assert(state().lease);
    db.prepare("UPDATE link_health SET lease_until=0 WHERE link_id=?").run(id); resetGate(); cycle(); assert.equal(state().lease, null);
    const rules = [{ name: "Same", target: link.target, conditions: { languages: ["fr"] } }, { name: "Unavailable", target: "https://example.com/unavailable", conditions: { languages: ["en"] } }];
    // Seed normalized rules without an unrelated DNS ban lookup in this offline test.
    runCode(`const routing=require(${JSON.stringify(path.join(root, "server/link-routing"))});await db('link_routing').insert({link_id:${id},revision:1,rules:JSON.stringify(routing.normalize(${JSON.stringify(rules)}))})`);
    db.prepare("UPDATE link_health SET next_at=0 WHERE link_id=?").run(id); resetGate();
    runCode(`let calls=0;safe.send=async(u)=>{calls++;return{status:u.includes('unavailable')?503:204}};await h.run(await h.claim());assert.equal(calls,2);`);
    assert.equal(JSON.parse(state().results).length, 3); assert.equal(state().state, "attention");
    await check(request("PUT", "/api/links/" + link.id + "/routing", { rules: [], revision: 1 }, session));
    db.prepare("UPDATE links SET target='https://example.com/changed' WHERE id=?").run(id);
    current = await check(request("GET", endpoint, undefined, session)); assert.equal(current.state, "stale"); assert.equal(current.results.length, 0);
    db.prepare("UPDATE link_health SET next_at=0 WHERE link_id=?").run(id); resetGate();
    const previousHash = state().source_hash, previousCheck = state().checked_at;
    cycle(`safe.send=async()=>{await db('links').where({id:${id}}).update({target:'https://example.com/changed-again'});return{status:200}}`);
    assert.equal(state().source_hash, previousHash); assert.equal(state().checked_at, previousCheck, "Obsolete in-flight result is discarded");
    assert.equal((await check(request("GET", endpoint, undefined, session))).state, "stale"); assert.equal(state().lease, null);
    db.prepare("UPDATE link_routing SET rules='broken-json' WHERE link_id=?").run(id);
    db.prepare("UPDATE link_health SET next_at=0,lease=?,lease_until=0 WHERE link_id=?").run(randomUUID(), id);
    current = await check(request("GET", endpoint, undefined, session)); assert.equal(current.state, "configuration_invalid"); assert.equal(current.overdue, true);
    resetGate(); runCode(`let calls=0;safe.send=async()=>{calls++;return{status:200}};await h.run(await h.claim());assert.equal(calls,0)`);
    assert.equal(state().lease, null); assert.equal(state().state, "configuration_invalid");
    db.prepare("UPDATE link_routing SET rules='[]' WHERE link_id=?").run(id);
    db.prepare("UPDATE link_health SET results='bad-json' WHERE link_id=?").run(id);
    current = await check(request("GET", endpoint, undefined, session)); assert.equal(current.state, "results_unavailable"); assert.deepEqual(current.results, []);
    db.prepare("UPDATE link_health SET next_at=0 WHERE link_id=?").run(id); resetGate(); cycle(`safe.send=async()=>{throw Object.assign(new Error('private data'),{code:'ADDRESS_DENIED'})}`);
    assert.equal(state().state, "attention"); assert.equal(JSON.parse(state().results)[0].code, "ADDRESS_DENIED");
    runCode(`const read=require(${JSON.stringify(path.join(root, "scripts/destination-health.cjs"))});const result=read(${JSON.stringify(database)});assert(result.enabled>=1);assert(result.attention>=1);assert(result.worker_age_seconds>=0);assert.deepEqual(Object.keys(result).sort(),['attention','enabled','overdue','worker_age_seconds']);assert.throws(()=>read('/tmp/not-an-existing-health-database'));`);
    const revisionBefore = state().revision;
    db.exec("CREATE TRIGGER reject_health_event BEFORE INSERT ON link_history WHEN NEW.action='health_configured' BEGIN SELECT RAISE(ABORT,'test rollback'); END");
    assert.equal((await request("PUT", endpoint, { ...config, revision: revisionBefore }, session)).status, 500);
    db.exec("DROP TRIGGER reject_health_event"); assert.equal(state().revision, revisionBefore);
    const race = await Promise.all([request("PUT", endpoint, { ...config, revision: revisionBefore }, session), request("PUT", endpoint, { ...config, revision: revisionBefore }, session)]);
    assert.deepEqual(race.map(row => row.status).sort(), [200, 409]);
    db.prepare("UPDATE users SET auth_version=auth_version+1 WHERE id=?").run(owner); resetGate();
    cycle(`safe.send=async()=>{throw new Error('Must not request after owner revocation')}`); assert.equal(state().state, "authorization_required");
    db.prepare("UPDATE users SET auth_version=auth_version-1 WHERE id=?").run(owner); // Disposable account only.
    current = await check(request("GET", endpoint, undefined, session));
    await check(request("PUT", endpoint, { enabled: false, interval_hours: 24, revision: current.revision }, session));
    resetGate(); runCode(`assert.equal(await h.claim(),null)`);
    await check(request("POST", endpoint + "/check", { revision: current.revision + 1 }, session), 409);
    await request("DELETE", "/api/tokens/" + writer.id, undefined, session);
    await check(request("PUT", endpoint, { ...config, revision: current.revision + 1 }, session, wh), 401);
    const down = code(`await require(${JSON.stringify(path.join(root, "server/migrations/20260914080000_destination_health"))}).down(db)`); assert.notEqual(down.status, 0);
    assert.equal(db.pragma("quick_check", { simple: true }), "ok"); assert.deepEqual(db.pragma("foreign_key_check"), []);
    console.log("PASS: opt-in health API/UI routes, owner/scoped/CSRF boundaries, revision and transactional rollback, HEAD classification, SSRF policy, no visit mutation, global rate gate, crash/restart recovery, source and authorization rechecks, private events and guarded downgrade");
  } finally { db.close(); }
};
