const assert = require("node:assert/strict");
const { randomUUID, createHmac } = require("node:crypto");
const { spawnSync } = require("node:child_process");
const path = require("node:path");
const Database = require("better-sqlite3");

module.exports = async ({ request, session, database, account, restart, root, directory, env }) => {
  const db = new Database(database), owner = db.prepare("SELECT id FROM users WHERE email=?").get(account.email).id;
  const prefix = "privacy-" + randomUUID(), ua = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1";
  const check = async (response, expected = 200) => { response = await response; assert.equal(response.status, expected, await response.clone().text()); return response.json(); };
  const create = async (suffix, more = {}) => check(request("POST", "/api/links", { customurl: prefix + suffix, target: "https://192.0.2.1/default", ...more }, session), 201);
  const processCode = code => spawnSync(process.execPath, ["-e", `(async()=>{${code};await require(${JSON.stringify(path.join(root, "server/knex.js"))}).destroy()})().catch(e=>{console.error(e.message);process.exit(1)})`], { cwd: directory, env, encoding: "utf8", timeout: 30000 });
  const privacyPath = JSON.stringify(path.join(root, "server/analytics-privacy.js"));
  const purge = (now = Date.now()) => processCode(`await require(${privacyPath}).purge(${now})`);
  const retention = (method, tail = "", body, cookie = session, headers) => request(method, "/api/analytics/retention" + tail, body, cookie, headers);
  try {
    const link = await create("-tracking", { max_visits: 10 });
    const id = db.prepare("SELECT id FROM links WHERE uuid=?").get(link.id).id;
    const tracking = (method, body, cookie = session, headers) => request(method, "/api/links/" + link.id + "/tracking", body, cookie, headers);
    let current = await check(tracking("GET")); assert.equal(current.enabled, true); assert.equal(current.revision, 0);
    const response = await tracking("GET"); assert.match(response.headers.get("cache-control"), /no-store/);
    const job = { link: { id, user_id: owner }, ip: "127.0.0.1", userAgent: ua, referrer: "https://example.invalid/" };
    const worker = value => processCode(`await require(${JSON.stringify(path.join(root, "server/queues/visit.js"))})({data:${JSON.stringify(value)}})`);
    const counter = () => db.prepare("SELECT visit_count FROM links WHERE id=?").get(id).visit_count;
    assert.equal(worker(job).status, 0); assert.equal(counter(), 1, "Legacy queue payload supported before privacy changes");
    current = await check(tracking("PUT", { enabled: false, revision: 0 })); assert.equal(current.revision, 1);
    for (const value of [job, { ...job, tracking_revision: 1 }, { ...job, tracking_revision: -1 }]) assert.equal(worker(value).status, 0);
    assert.equal((await request("GET", "/" + link.address, undefined, undefined, { "User-Agent": ua })).status, 302);
    await new Promise(resolve => setTimeout(resolve, 100)); assert.equal(counter(), 1);
    assert.equal(db.prepare("SELECT redirect_count FROM links WHERE id=?").get(id).redirect_count, 1, "Quota still counts public redirects while analytics is off");
    assert.equal(db.prepare("SELECT SUM(total) n FROM visits WHERE link_id=?").get(id).n, 1, "Opt-out does not erase old analytics");
    await check(tracking("PUT", { enabled: true, revision: 0 }), 409);
    for (const body of [{ enabled: "false", revision: 1 }, { enabled: true }, { enabled: true, revision: -1 }, { enabled: true, revision: 1, user_id: owner }]) await check(tracking("PUT", body), 400);
    await check(tracking("PUT", { enabled: true, revision: 1 }, session, { Origin: "https://evil.invalid" }), 403);
    const competing = await Promise.all([tracking("PUT", { enabled: true, revision: 1 }), tracking("PUT", { enabled: true, revision: 1 })]);
    assert.deepEqual(competing.map(r => r.status).sort(), [200, 409]);
    assert.equal(worker(job).status, 0); assert.equal(worker({ ...job, tracking_revision: 1 }).status, 0); assert.equal(counter(), 1, "Old jobs stay suppressed after tracking is re-enabled");
    assert.equal(worker({ ...job, tracking_revision: 2 }).status, 0); assert.equal(counter(), 2);
    // A toggle between worker validation and its write is caught again inside
    // the same transaction that owns the counter and aggregate writes.
    await check(tracking("PUT", { enabled: false, revision: 2 }));
    const lateWrite = processCode(`await require(${JSON.stringify(path.join(root, "server/queries/visit.queries.js"))}).add(${JSON.stringify({ link_id: id, user_id: owner, tracking_revision: 2, browser: "safari", os: "ios", country: "FR", referrer: "Direct" })})`);
    assert.equal(lateWrite.status, 0); assert.equal(counter(), 2);
    db.prepare("UPDATE link_tracking SET enabled=2 WHERE link_id=?").run(id);
    await check(tracking("GET"), 503);
    assert.equal((await request("GET", "/" + link.address, undefined, undefined, { "User-Agent": ua })).status, 302, "Bad analytics policy must not break a public redirect");
    assert.equal(counter(), 2); db.prepare("UPDATE link_tracking SET enabled=0 WHERE link_id=?").run(id);
    const foreign = Number(db.prepare("INSERT INTO users(email,password,role,verified) SELECT ?,password,'ADMIN',1 FROM users WHERE id=?").run(prefix + "@example.invalid", owner).lastInsertRowid);
    const foreignSession = require("jsonwebtoken").sign({ iss: "ApiAuth", sub: foreign }, env.JWT_SECRET, { expiresIn: 600 });
    await check(tracking("GET", undefined, foreignSession), 404); await check(tracking("PUT", { enabled: true, revision: 3 }, foreignSession), 404);
    assert.equal((await request("GET", "/link/tracking/" + link.id, undefined, foreignSession, { Accept: "text/html" })).status, 404);
    await check(request("GET", "/api/links/" + link.id + "/tracking"), 401);
    const token = async scopes => check(request("POST", "/api/tokens", { name: "Privacy", scopes, domain_scope: "default" }, session), 201);
    const reader = await token(["links:read"]), writer = await token(["links:update"]), creator = await token(["links:create"]);
    const readerHeader = { "X-API-Key": reader.token }, writerHeader = { "X-API-Key": writer.token };
    await check(tracking("GET", undefined, undefined, readerHeader));
    await check(tracking("PUT", { enabled: true, revision: 3 }, undefined, readerHeader), 403);
    await check(tracking("PUT", { enabled: false, revision: 3 }, undefined, writerHeader));
    await check(tracking("GET", undefined, undefined, writerHeader), 403);
    assert.equal((await request("GET", "/link/tracking/" + link.id, undefined, session, readerHeader)).status, 403);
    const domain = Number(db.prepare("INSERT INTO domains(uuid,address,user_id) VALUES(?,?,?)").run(randomUUID(), prefix + ".invalid", owner).lastInsertRowid);
    db.prepare("UPDATE links SET domain_id=? WHERE id=?").run(domain, id);
    await check(tracking("GET", undefined, undefined, readerHeader), 404);
    db.prepare("UPDATE links SET domain_id=NULL WHERE id=?").run(id);
    db.prepare("UPDATE links SET deleted_at=? WHERE id=?").run(Date.now(), id); await check(tracking("GET"), 410);
    db.prepare("UPDATE links SET deleted_at=NULL WHERE id=?").run(id);
    const transfer = async (format, content, headers) => {
      const input = { format, content, conflict: "rename" };
      const preview = await check(request("POST", "/api/transfer/preview", input, session, headers));
      if (headers) return preview;
      assert.equal(preview.valid, true, JSON.stringify(preview));
      const result = await check(request("POST", "/api/transfer/commit", { ...input, preview_token: preview.preview_token }, session), 201);
      return check(request("GET", "/api/links/" + result.created[0].id + "/tracking", undefined, session));
    };
    for (const format of ["json", "csv"]) {
      const exported = await request("GET", "/api/transfer/export?format=" + format + "&q=" + link.address, undefined, session);
      assert.equal(exported.status, 200); const content = await exported.text();
      assert.equal((await transfer(format, content)).enabled, false, format + " opt-out survives export/import");
      assert.equal((await transfer(format, content, { "X-API-Key": creator.token })).valid, false, "Opt-out import requires links:update");
    }
    const oldImport = JSON.stringify([{ address: prefix + "-old-file", target: "https://192.0.2.1/" }]);
    assert.equal((await transfer("json", oldImport)).enabled, true, "Old exports keep the historical default");
    await request("DELETE", "/api/tokens/" + writer.id, undefined, session);
    await check(tracking("PUT", { enabled: true, revision: 4 }, undefined, writerHeader), 401);
    const down = spawnSync(process.execPath, [path.join(root, "node_modules/knex/bin/cli.js"), "--knexfile", path.join(root, "knexfile.js"), "migrate:down", "20260914050000_analytics_privacy.js"], { cwd: directory, env, encoding: "utf8", timeout: 30000 });
    assert.notEqual(down.status, 0, "Never discard queue revisions or opt-outs on rollback");
    let policy = await check(retention("GET")); assert.equal(policy.days, 0); assert.equal(policy.revision, 0);
    await check(request("GET", "/api/analytics/retention"), 401);
    await check(retention("GET", "", undefined, session, readerHeader), 403);
    assert.equal((await request("GET", "/settings/retention", undefined, session, readerHeader)).status, 403);
    db.prepare("UPDATE users SET role='USER' WHERE id=?").run(foreign);
    await check(retention("GET", "", undefined, foreignSession), 403);
    await check(retention("POST", "/preview", { days: 30, revision: 0 }, foreignSession), 403);
    assert.equal((await request("GET", "/settings/retention", undefined, foreignSession, { Accept: "text/html" })).status, 403);
    for (const body of [{ days: -1, revision: 0 }, { days: "30", revision: 0 }, { days: 36501, revision: 0 }, { days: 1 }, { days: 1.5, revision: 0 }, { days: 1, revision: 0, immediate: true }]) await check(retention("POST", "/preview", body), 400);
    await check(retention("POST", "/preview", { days: 30, revision: 0 }, session, { Origin: "https://evil.invalid" }), 403);
    const preview = await check(retention("POST", "/preview", { days: 30, revision: 0 }));
    await check(retention("PUT", "", { confirmation: preview.confirmation }), 400);
    await check(retention("PUT", "", { confirmation: preview.confirmation + "x", acknowledge_deletion: true }), 400);
    db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(foreign);
    await check(retention("PUT", "", { confirmation: preview.confirmation, acknowledge_deletion: true }, foreignSession), 409);
    const receipt = JSON.parse(Buffer.from(preview.confirmation.split(".")[0], "base64url")); receipt.expires = Date.now() - 1;
    const encoded = Buffer.from(JSON.stringify(receipt)).toString("base64url");
    const expired = encoded + "." + createHmac("sha256", env.JWT_SECRET).update("analytics-retention-v1\0" + encoded).digest("hex");
    await check(retention("PUT", "", { confirmation: expired, acknowledge_deletion: true }), 409);
    const countBefore = db.prepare("SELECT COUNT(*) n FROM visits").get().n;
    assert.equal(purge().status, 0); assert.equal(db.prepare("SELECT COUNT(*) n FROM visits").get().n, countBefore, "Disabled retention never purges");
    const allLinks = db.prepare("SELECT id,visit_count,redirect_count,target FROM links ORDER BY id").all();
    const midnight = Math.floor(Date.now() / 86400000) * 86400000, cutoff = midnight - 30 * 86400000;
    const date = n => new Date(n).toISOString().slice(0, 19).replace("T", " ");
    const insertVisit = db.prepare("INSERT INTO visits(link_id,user_id,created_at,total,countries,referrers) VALUES(?,?,?,1,'{}','{}')");
    const oldID = Number(insertVisit.run(id, owner, date(cutoff - 1)).lastInsertRowid);
    const boundaryID = Number(insertVisit.run(id, owner, date(cutoff)).lastInsertRowid);
    policy = await check(retention("PUT", "", { confirmation: preview.confirmation, acknowledge_deletion: true }));
    assert.equal(policy.days, 30); assert.equal(policy.revision, 1);
    await check(retention("PUT", "", { confirmation: preview.confirmation, acknowledge_deletion: true }), 409);
    assert(db.prepare("SELECT id FROM visits WHERE id=?").get(oldID), "Saving policy does not delete synchronously");
    db.exec("CREATE TRIGGER privacy_purge_fail BEFORE DELETE ON visits BEGIN SELECT RAISE(ABORT,'private test data'); END");
    const failed = purge(midnight); assert.notEqual(failed.status, 0); assert(!failed.stderr.includes("private test data"), "Caller only emits sanitized errors");
    assert(db.prepare("SELECT id FROM visits WHERE id=?").get(oldID), "Batch rollback preserves data");
    db.exec("DROP TRIGGER privacy_purge_fail");
    assert.match((await check(retention("GET"))).last_error, /failed/);
    const done = purge(midnight); assert.equal(done.status, 0, done.stderr);
    assert.equal(db.prepare("SELECT id FROM visits WHERE id=?").get(oldID), undefined);
    assert(db.prepare("SELECT id FROM visits WHERE id=?").get(boundaryID), "UTC cutoff is exclusive");
    policy = await check(retention("GET")); assert.equal(policy.last_error, null); assert(policy.deleted_buckets > 0); assert.equal(policy.last_run, new Date(midnight).toISOString());
    assert.deepEqual(db.prepare("SELECT id,visit_count,redirect_count,target FROM links ORDER BY id").all(), allLinks, "Retention preserves links and lifetime counters");
    const cacheCheck = processCode(`
      const redis=require(${JSON.stringify(path.join(root, "server/redis.js"))});
      const envPath=${JSON.stringify(path.join(root, "server/env.js"))};
      require.cache[require.resolve(envPath)].exports={...require(envPath),REDIS_ENABLED:true};
      redis.client={get:async()=>{throw new Error('stale cache read')},set:()=>{throw new Error('stale cache write')}};
      await require(${JSON.stringify(path.join(root, "server/queries/visit.queries.js"))}).find({link_id:${id}})
    `);
    assert.equal(cacheCheck.status, 0, cacheCheck.stderr);
    const bulkIDs = [];
    db.transaction(() => { for (let i = 0; i < 1005; i++) bulkIDs.push(Number(insertVisit.run(id, owner, date(cutoff - 1000)).lastInsertRowid)); })();
    const batched = purge(midnight); assert.equal(batched.status, 0, batched.stderr);
    assert.equal(db.prepare("SELECT COUNT(*) n FROM visits WHERE id BETWEEN ? AND ?").get(bulkIDs[0], bulkIDs.at(-1)).n, 0, "Multiple bounded batches finish eligible rows");
    const disable = await check(retention("POST", "/preview", { days: 0, revision: policy.revision }));
    await check(retention("PUT", "", { confirmation: disable.confirmation }));
    const retainedID = Number(insertVisit.run(id, owner, date(cutoff - 1000)).lastInsertRowid);
    assert.equal(purge().status, 0); assert(db.prepare("SELECT id FROM visits WHERE id=?").get(retainedID));
    await restart(); assert.equal((await check(tracking("GET"))).enabled, false); assert.equal((await check(retention("GET"))).days, 0);
    db.prepare("UPDATE analytics_retention SET days=-1 WHERE id=1").run();
    assert.notEqual(purge().status, 0); assert(db.prepare("SELECT id FROM visits WHERE id=?").get(retainedID));
    db.prepare("UPDATE analytics_retention SET days=0 WHERE id=1").run();
    assert.equal(db.pragma("quick_check", { simple: true }), "ok"); assert.deepEqual(db.pragma("foreign_key_check"), []);
    console.log("PASS: opt-outs, legacy/stale queue suppression, atomic write recheck, redirect quotas, ownership/scopes/domains/CSRF, import/export preservation, admin-only signed retention preview/confirmation, UTC purge/rollback/recovery, restart and guarded downgrade");
  } finally { db.close(); }
};
