const assert = require("node:assert/strict");
const { randomUUID, createHmac } = require("node:crypto");
const { spawnSync } = require("node:child_process");
const path = require("node:path");
const Database = require("better-sqlite3");
module.exports = async ({ request, session, database, account, restart, root, directory, env }) => {
  const db = new Database(database), owner = db.prepare("SELECT id FROM users WHERE email=?").get(account.email).id;
  const check = async (response, expected = 200) => { response = await response; assert.equal(response.status, expected, await response.clone().text()); return response.status === 204 ? null : response.json(); };
  const config = { name: "Test hook", url: "https://hooks.example.com/incoming?private=never-in-events", enabled: true, events: ["link.created", "link.updated", "link.trashed", "link.restored"] };
  const hook = (method, tail = "", body, cookie = session, headers) => request(method, "/api/webhooks" + tail, body, cookie, headers);
  const code = value => spawnSync(process.execPath, ["-e", `(async()=>{${value};await require(${JSON.stringify(path.join(root, "server/knex"))}).destroy()})().catch(e=>{console.error(e.stack);process.exit(1)})`], { cwd: directory, env, encoding: "utf8", timeout: 30000 });
  const modulePath = JSON.stringify(path.join(root, "server/webhooks"));
  const processDelivery = (id, status, error) => code(`const h=require(${modulePath});const safe=require(${JSON.stringify(path.join(root, "server/safe-http"))}); const db=require(${JSON.stringify(path.join(root, "server/knex"))});
    safe.send=async(url,options)=>{${error ? `throw Object.assign(new Error("private receiver detail"),{code:${JSON.stringify(error)}});` : `console.log(JSON.stringify({url,options}));return {status:${status}};`}};
    const row=await h.claim(Date.now());if(!row||row.id!==${JSON.stringify(id)})throw new Error("Unexpected claim");await h.deliver(row)`);
  const createLink = () => check(request("POST", "/api/links", { customurl: "hooks-" + randomUUID(), target: "https://192.0.2.1/private?secret=do-not-export" }, session), 201);
  let current, originalOptions = env.NODE_OPTIONS;
  try {
    const transport = code(`await require(${JSON.stringify(path.join(root, "tests/safe-http.cjs"))})(${JSON.stringify(root)})`);
    assert.equal(transport.status, 0, transport.stderr);
    console.log(transport.stdout.trim());
    env.NODE_OPTIONS = "--require=" + path.join(root, "tests/webhooks-offline.cjs"); await restart();
    const page = await request("GET", "/settings/integrations", undefined, session);
    assert.equal(page.status, 200);
    const html = await page.text();
    assert.match(html, /id="hook-form" method="post" action="\/api\/v2\/webhooks" aria-labelledby="hook-editor-title"/);
    assert.match(html, /id="hook-form-error"[^>]*role="alert"[^>]*tabindex="-1"[^>]*hidden/);
    await check(request("GET", "/api/webhooks"), 401); await check(request("GET", "/api/events"), 401);
    for (const body of [{ ...config, url: "http://hooks.example.com" }, { ...config, url: "https://mixed.example.com" }, { ...config, events: ["visit.created"] }, { ...config, enabled: "true" }, { ...config, name: "" }, { ...config, user_id: 2 }]) await check(hook("POST", "", body), 400);
    await check(hook("POST", "", config, session, { Origin: "https://evil.invalid" }), 403);
    current = await check(hook("POST", "", config), 201); assert.match(current.secret, /^whsec_[\w-]{43}$/);
    const secret = current.secret, encrypted = db.prepare("SELECT secret FROM webhooks WHERE id=?").get(current.id).secret;
    assert(!encrypted.includes(secret)); assert.match(encrypted, /^v1\./);
    const listed = await check(hook("GET")); assert(!JSON.stringify(listed).includes(secret)); assert.equal(listed.data[0].revision, 1);
    const foreign = Number(db.prepare("INSERT INTO users(email,password,role,verified) SELECT ?,password,'ADMIN',1 FROM users WHERE id=?").run(randomUUID() + "@example.invalid", owner).lastInsertRowid);
    const jwt = require("jsonwebtoken"), foreignSession = jwt.sign({ iss: "ApiAuth", sub: foreign }, env.JWT_SECRET, { expiresIn: 600 });
    assert.equal((await check(hook("GET", "", undefined, foreignSession))).data.length, 0);
    await check(hook("PUT", "/" + current.id, { ...config, revision: 1 }, foreignSession), 404);
    await check(hook("GET", "/" + current.id + "/deliveries", undefined, foreignSession), 404);
    const token = (scopes, domain_scope = "all") => check(request("POST", "/api/tokens", { name: "Integrations", scopes, domain_scope }, session), 201);
    const reader = await token(["webhooks:read", "events:read"]), writer = await token(["webhooks:write"]), limited = await token(["webhooks:read", "webhooks:write", "events:read"], "default");
    const rh = { "X-API-Key": reader.token }, wh = { "X-API-Key": writer.token };
    await check(hook("GET", "", undefined, undefined, rh)); await check(hook("POST", "", config, undefined, rh), 403);
    await check(hook("GET", "", undefined, undefined, wh), 403);
    for (const route of ["/api/webhooks", "/api/events"]) await check(request("GET", route, undefined, session, { "X-API-Key": limited.token }), 403);
    assert.equal((await request("GET", "/api/events/stream", undefined, session, rh)).status, 403);
    assert.equal((await request("GET", "/settings/integrations", undefined, session, rh)).status, 403);
    await check(request("GET", "/api/events?after=not-a-number", undefined, session), 400);
    const before = db.prepare("SELECT COUNT(*) n FROM management_events").get().n;
    const forced = code(`const db=require(${JSON.stringify(path.join(root, "server/knex"))});try{await db.transaction(async t=>{await require(${JSON.stringify(path.join(root, "server/link-history"))}).record(t,{id:${db.prepare("SELECT id FROM links LIMIT 1").get().id},uuid:${JSON.stringify(randomUUID())},user_id:${owner}},"updated",["target"],{id:${owner}});throw new Error("rollback")})}catch(e){if(e.message!=="rollback")throw e}`);
    assert.equal(forced.status, 0, forced.stderr); assert.equal(db.prepare("SELECT COUNT(*) n FROM management_events").get().n, before, "Event/outbox writes roll back with link mutation");
    const link = await createLink();
    let delivery = (await check(hook("GET", "/" + current.id + "/deliveries"))).data[0]; assert.equal(delivery.state, "pending");
    assert.equal(delivery.attempts, 0, "HTTP request must not send synchronously");
    const first = processDelivery(delivery.id, 503); assert.equal(first.status, 0, first.stderr);
    const captured = JSON.parse(first.stdout.trim()); assert(!captured.options.body.includes("do-not-export")); assert(!captured.options.body.includes("private="));
    const headers = captured.options.headers;
    assert.equal(headers["X-Kutt-Signature"], "v1=" + createHmac("sha256", secret).update(headers["X-Kutt-Timestamp"] + "." + captured.options.body).digest("hex"));
    const verify = require(path.join(root, "examples/verify-webhook.cjs"));
    const lower = Object.fromEntries(Object.entries(headers).map(([key, value]) => [key.toLowerCase(), value]));
    assert.equal(verify(Buffer.from(captured.options.body), lower, secret).id, headers["X-Kutt-Event-Id"]);
    assert.throws(() => verify(Buffer.from(captured.options.body + " "), lower, secret), /Invalid webhook/);
    assert.throws(() => verify(Buffer.from(captured.options.body), lower, secret, Date.now() + 400000), /Invalid webhook/);
    assert.throws(() => verify(Buffer.from(captured.options.body), { ...lower, "x-kutt-event-id": randomUUID() }, secret), /Invalid webhook/);
    assert.equal(JSON.parse(captured.options.body).data.link_id, link.id);
    const state = () => db.prepare("SELECT * FROM webhook_deliveries WHERE id=?").get(delivery.id);
    assert.equal(state().state, "pending"); assert.equal(state().attempts, 1); assert(state().next_at > Date.now() + 20000);
    const early = code(`if(await require(${modulePath}).claim(Date.now()))throw new Error("Early retry")`); assert.equal(early.status, 0, early.stderr);
    db.prepare("UPDATE webhook_deliveries SET next_at=0 WHERE id=?").run(delivery.id);
    const success = processDelivery(delivery.id, 204); assert.equal(success.status, 0, success.stderr);
    assert.equal(state().state, "delivered"); assert.equal(state().total_attempts, 2);
    assert.equal(JSON.parse(success.stdout.trim()).options.headers["X-Kutt-Event-Id"], headers["X-Kutt-Event-Id"], "Stable receiver idempotency identifier across retries");
    const queued = await check(hook("POST", "/" + current.id + "/test", { revision: 1 }), 202);
    delivery = { id: queued.delivery_id };
    const denied = processDelivery(delivery.id, null, "ADDRESS_DENIED"); assert.equal(denied.status, 0, denied.stderr); assert.equal(state().state, "failed"); assert.equal(state().error, "ADDRESS_DENIED");
    assert.equal((await hook("POST", "/" + current.id + "/retry", { delivery_id: delivery.id, revision: 1 })).status, 202);
    assert.equal(state().state, "pending");
    await check(hook("PUT", "/" + current.id, { ...config, enabled: false, revision: 1 }, undefined, wh)); assert.equal(state().state, "cancelled");
    await check(hook("POST", "/" + current.id + "/test", { revision: 2 }), 409);
    const race = await Promise.all([hook("PUT", "/" + current.id, { ...config, revision: 2 }), hook("PUT", "/" + current.id, { ...config, revision: 2 })]);
    assert.deepEqual(race.map(r => r.status).sort(), [200, 409]);
    const rotation = await check(hook("POST", "/" + current.id + "/rotate", { revision: 3 })); assert.notEqual(rotation.secret, secret); current = rotation;
    await check(hook("POST", "/" + current.id + "/rotate", { revision: 3 }), 409);
    assert.equal((await hook("GET")).headers.get("cache-control"), "private, no-store");
    const queuedCrash = await check(hook("POST", "/" + current.id + "/test", { revision: 4 }), 202); delivery = { id: queuedCrash.delivery_id };
    assert.equal(code(`if(!await require(${modulePath}).claim(Date.now()))throw new Error("No claim")`).status, 0); assert.equal(state().state, "delivering");
    await restart(); assert.equal(state().state, "delivering");
    db.prepare("UPDATE webhook_deliveries SET lease_until=0 WHERE id=?").run(delivery.id);
    assert.equal(processDelivery(delivery.id, 200).status, 0); assert.equal(state().state, "delivered"); assert.equal(state().total_attempts, 2);
    const exhausted = await check(hook("POST", "/" + current.id + "/test", { revision: 4 }), 202); delivery = { id: exhausted.delivery_id };
    db.prepare("UPDATE webhook_deliveries SET attempts=5,total_attempts=5 WHERE id=?").run(delivery.id);
    assert.equal(processDelivery(delivery.id, 503).status, 0); assert.equal(state().state, "failed"); assert.equal(state().attempts, 6);
    const crashLimit = await check(hook("POST", "/" + current.id + "/test", { revision: 4 }), 202); delivery = { id: crashLimit.delivery_id };
    db.prepare("UPDATE webhook_deliveries SET state='delivering',attempts=6,lease=?,lease_until=0 WHERE id=?").run(randomUUID(), delivery.id);
    assert.equal(code(`if(await require(${modulePath}).claim(Date.now()))throw new Error("Exhausted claim")`).status, 0);
    assert.equal(state().state, "failed"); assert.equal(state().error, "ATTEMPTS_EXHAUSTED");
    const feed = await check(request("GET", "/api/events", undefined, session, rh)); assert(feed.data.some(e => e.type === "webhook.test")); assert(!JSON.stringify(feed).includes("do-not-export"));
    assert.equal((await check(request("GET", "/api/events", undefined, foreignSession))).data.length, 0);
    const streamResponse = await request("GET", "/api/events/stream?after=" + feed.cursor, undefined, session);
    assert.equal(streamResponse.status, 200); assert.match(streamResponse.headers.get("content-type"), /text\/event-stream/); assert.equal(streamResponse.headers.get("x-accel-buffering"), "no");
    const stream = streamResponse.body.getReader(); let text = "";
    const liveLink = await createLink();
    while (!text.includes(liveLink.id)) { const chunk = await stream.read(); assert(!chunk.done); text += Buffer.from(chunk.value).toString(); }
    assert.match(text, /event: management/);
    db.prepare("UPDATE users SET auth_version=auth_version+1 WHERE id=?").run(owner);
    while (!text.includes("event: revoked")) { const chunk = await stream.read(); assert(!chunk.done); text += Buffer.from(chunk.value).toString(); }
    await stream.cancel();
    const pending = db.prepare("SELECT id FROM webhook_deliveries WHERE state='pending' AND webhook_id=?").get(current.id);
    assert(pending); assert.equal(processDelivery(pending.id, 200).status, 0); assert.equal(db.prepare("SELECT state FROM webhook_deliveries WHERE id=?").get(pending.id).state, "cancelled");
    db.prepare("UPDATE users SET auth_version=auth_version-1 WHERE id=?").run(owner); // Disposable fixture only; production revisions must never be lowered.
    await request("DELETE", "/api/tokens/" + writer.id, undefined, session);
    await check(hook("PUT", "/" + current.id, { ...config, revision: 4 }, session, wh), 401);
    const down = code(`await require(${JSON.stringify(path.join(root, "server/migrations/20260914060000_webhooks_events"))}).down(require(${JSON.stringify(path.join(root, "server/knex"))}))`);
    assert.notEqual(down.status, 0, "Never discard live integration history on schema rollback");
    await check(hook("DELETE", "/" + current.id, { revision: 4 }), 204);
    assert.equal(db.prepare("SELECT COUNT(*) n FROM webhook_deliveries WHERE webhook_id=?").get(current.id).n, 0);
    assert(db.prepare("SELECT id FROM links WHERE uuid=?").get(link.id), "Deleting webhook preserves links");
    assert.equal(db.pragma("quick_check", { simple: true }), "ok"); assert.deepEqual(db.pragma("foreign_key_check"), []);
    console.log("PASS: private encrypted webhook configuration, scopes/owner/domain/CSRF, transactional outbox, signed asynchronous delivery, retry/backoff/cancellation, secret rotation, crash lease recovery, authenticated live event revocation and guarded downgrade");
  } finally { if (originalOptions === undefined) delete env.NODE_OPTIONS; else env.NODE_OPTIONS = originalOptions; await restart(); db.close(); }
};
