const { Router } = require("express");
const auth = require("../handlers/auth.handler");
const analytics = require("../handlers/analytics.handler");
const helpers = require("../handlers/helpers.handler");
const asyncHandler = require("../utils/asyncHandler");
const router = Router();
const { sessionOnly } = require("../handlers/tokens.handler");
router.use("/retention", sessionOnly);
router.use(asyncHandler(auth.apikey), asyncHandler(auth.jwt), analytics.boundary);
const privacy = require("../handlers/privacy.handler");
router.get("/retention", privacy.boundary, asyncHandler(privacy.getRetention));
router.post("/retention/preview", privacy.boundary, helpers.rateLimit({ window: 60, limit: 20 }), asyncHandler(privacy.previewRetention));
router.put("/retention", privacy.boundary, helpers.rateLimit({ window: 60, limit: 20 }), asyncHandler(privacy.saveRetention));
router.get("/", helpers.rateLimit({ window: 60, limit: 30 }), asyncHandler(analytics.get));
module.exports = router;
